library(ggplot2)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
baltimore <- subset(NEI, NEI$fips == "24510")
g <- ggplot(baltimore, aes(year, Emissions)) + labs(title = "Fine particle emissions in Baltimore") + xlab("") + ylab(PM[2.5]~" emissions in tons")
plot3<- g + geom_bar(stat="identity") +facet_grid(.~type) 
print(plot3)
dev.copy(png,"plot3.png", width=480, height=480)
dev.off()